# Generated by Django 4.1.3 on 2022-11-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('register_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['register_date'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['delivery_date', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('NIT', 'Número de identificación tributaria')], default='CC', max_length=3)),
                ('document_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField()),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.person')),
            ],
            options={
                'verbose_name_plural': 'Providers',
                'ordering': ['register_date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.provider')),
            ],
            options={
                'verbose_name_plural': 'Provider Prices',
                'ordering': ['id_provider', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_providers', models.IntegerField()),
                ('avg_daily_product_income', models.IntegerField()),
                ('route_type', models.CharField(choices=[('MORNING_ROUTE', 'Ruta de la mañana'), ('AFTERNOON_ROUTE', 'Ruta de la tarde'), ('NIGHT_ROUTE', 'Ruta de la noche')], default='MORNING_ROUTE', max_length=20)),
                ('locations', models.ManyToManyField(to='product_control.location')),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProductControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.delivery')),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.provider')),
                ('provider_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.providerprice')),
            ],
            options={
                'verbose_name_plural': 'Provider Product Control',
                'ordering': ['id_provider', 'id_delivery', 'quantity', 'provider_price', 'total_price', 'delivery_date'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.route'),
        ),
        migrations.CreateModel(
            name='ProductDispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_date', models.DateField()),
                ('dispatch_product_quantity', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='product_control.client')),
                ('id_dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_by', to='product_control.employee')),
                ('id_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.route')),
            ],
            options={
                'verbose_name_plural': 'Product Dispatch',
                'ordering': ['id_route', 'id_dispatched_by', 'id_client', 'dispatch_date', 'dispatch_product_quantity'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.municipality'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.person'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='id_delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to='product_control.employee'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='id_received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by', to='product_control.employee'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='id_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.route'),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.person')),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.person'),
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta débito'), ('CREDIT_CARD', 'Tarjeta crédito'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], default='CASH', max_length=11)),
                ('bank', models.CharField(choices=[('BANCO_AGRARIO', 'Banco Agrario'), ('BANCO_DAVIVIENDA', 'Banco Davivienda'), ('BANCO_DE_BOGOTA', 'Banco de Bogotá'), ('BANCOLOMBIA', 'Bancolombia'), ('BBVA_COLOMBIA', 'BBVA Colombia'), ('NO_APLICA', 'No aplica')], default='BANCOLOMBIA', max_length=25)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_representative', models.IntegerField(blank=True, null=True)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.person')),
            ],
            options={
                'verbose_name_plural': 'Billing Info',
                'ordering': ['id'],
            },
        ),
    ]
