# Generated by Django 4.1.3 on 2022-11-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0002_alter_productdispatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Persons'},
        ),
    ]
