# Generated by Django 4.1.3 on 2022-11-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdispatch',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.client'),
        ),
        migrations.AlterField(
            model_name='productdispatch',
            name='id_dispatched_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.employee'),
        ),
    ]
