# Generated by Django 4.1.3 on 2022-11-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0004_alter_productdispatch_id_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdispatch',
            options={'verbose_name_plural': 'Product Dispatch'},
        ),
    ]
