# Generated by Django 4.1.3 on 2022-11-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0005_alter_productdispatch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerproductcontrol',
            options={'ordering': ['id_provider', 'id_delivery', 'quantity', 'id_provider_price'], 'verbose_name_plural': 'Provider Product Control'},
        ),
        migrations.RemoveField(
            model_name='providerproductcontrol',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='route',
            name='avg_daily_product_income',
        ),
        migrations.CreateModel(
            name='ProviderPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_since', models.DateField()),
                ('payment_until', models.DateField()),
                ('payment_date', models.DateField()),
                ('id_billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.billinginfo')),
                ('id_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_control.provider')),
            ],
            options={
                'verbose_name_plural': 'Provider Payment',
            },
        ),
    ]
