# Generated by Django 4.1.3 on 2022-11-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0007_remove_route_n_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='id_representative',
        ),
    ]
