# Generated by Django 4.1.3 on 2022-11-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0008_remove_billinginfo_id_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_control.route'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
