# Generated by Django 4.1.3 on 2022-11-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0009_employee_id_route_alter_employee_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_route',
        ),
    ]
