# Generated by Django 4.1.3 on 2022-12-01 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0011_remove_providerpayment_id_billing_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerpayment',
            name='payment_since',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 19, 21, 24, 878353, tzinfo=datetime.timezone.utc)),
        ),
    ]
