# Generated by Django 4.1.3 on 2022-12-01 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0016_alter_providerpayment_payment_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerpayment',
            name='payment_since',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 22, 45, 5, 347917, tzinfo=datetime.timezone.utc)),
        ),
    ]
