# Generated by Django 4.1.3 on 2022-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0019_alter_providerpayment_payment_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerpayment',
            name='payment_since',
            field=models.DateField(),
        ),
    ]
