# Generated by Django 4.1.3 on 2022-12-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_control', '0020_alter_providerpayment_payment_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerproductcontrol',
            name='payment_amount',
            field=models.IntegerField(null=True),
        ),
    ]
